[custom.all.mandelbrot]
type = "local"
path = "."
ipkg = "mandelbrot.ipkg"
test = "test/test.ipkg"

[custom.all.mandelbrot-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

[custom.all.complex]
type = "github"
url  = "https://github.com/daniel-j-anderson-dev/complex_idris2.git"
commit = "main"
ipkg = "complex.ipkg"
